/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "STM32F103x6.h"
#include "STM32F103x6_GPIO_Driver.h"



void clock_init()
{
	//	GPIOA clock enable
	RCC_GPIOA_CLK_EN();

	//	GPIOB clock enable
	RCC_GPIOB_CLK_EN();
}



void GPIO_init()
{
	//	Configuring GPIOA p1 to be a Floating Input (0b0100)
	GPIO_PinConfig_t pin;
	pin.GPIO_PinNumber = GPIO_PIN_1;
	pin.GPIO_PinMode = GPIO_MODE_INPUT_FLO;
	MCAL_GPIO_Init(GPIOA, &pin);

	//	Configuring GPIOA p13 to be a Floating Input (0b0100)
	pin.GPIO_PinNumber = GPIO_PIN_13;
	MCAL_GPIO_Init(GPIOA, &pin);

	//	Configuring GPIOB p1 to be a Push-Pull Output with max speed = 10 MHz (0b0001)
	pin.GPIO_PinNumber = GPIO_PIN_1;
	pin.GPIO_PinMode = GPIO_MODE_OUTPUT_PP;
	pin.GPIO_Pin_OutputSpeed = GPIO_OUTPUT_SPEED_10MHz;
	MCAL_GPIO_Init(GPIOB, &pin);

	//	Configuring GPIOB p13 to be a Push-Pull Output with max speed = 10 MHz (0b0001)
	pin.GPIO_PinNumber = GPIO_PIN_13;
	MCAL_GPIO_Init(GPIOB, &pin);
}



int main(void)
{
	volatile unsigned int i;
	clock_init();
	GPIO_init();

	while(1)
	{
		//	Toggling GPIOB p1 ONCE every time the button gets closed(switched ON) [Single pressing]
		//	Button is connected to a pull-up resistor (PUR)
		if (MCAL_GPIO_ReadPin(GPIOA, GPIO_PIN_1) == 0)
		{
			MCAL_GPIO_TogglePin(GPIOB, GPIO_PIN_1);
			while (MCAL_GPIO_ReadPin(GPIOA, GPIO_PIN_1) == 0) ;
		}
		//	Toggling GPIOB p13 Non-Stop every time the button gets closed(switched ON) [Multi-pressing]
		//	Button is connected to a pull-down resistor (PDR)
		if (MCAL_GPIO_ReadPin(GPIOA, GPIO_PIN_13) == 1)
		{
			MCAL_GPIO_TogglePin(GPIOB, GPIO_PIN_13);
			for (i = 0; i < 1000; i++) ;	// arbitrary delay
		}
	}

	return 0;
}
