/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "STM32F103x6.h"
#include "STM32F103x6_GPIO_Driver.h"
#include "STM32F103x6_EXTI_Driver.h"
#include "LCD.h"



unsigned int IRQ_Flag = 0;

void EXTI_L9_PB_IRQHandlerCallback();



void _wait_ms(uint32_t time)
{
	uint32_t i, j;
	for (i = 0; i < time; i++)
		for (j = 0; j < 255; j++) ;
}



void clock_init()
{
	//	GPIOA clock enable
	RCC_GPIOA_CLK_EN();

	//	GPIOB clock enable
	RCC_GPIOB_CLK_EN();

	//	GPIOB clock enable
	RCC_AFIO_CLK_EN();
}



void EXTI_init()
{
	EXTI_PinConfig_t pin;
	pin.EXTI_Lx_Pyx      = EXTI_L9_PB9;
	pin.EXTI_TriggerCase = EXTI_Trigger_Falling;
	pin.P_IRQ_CallBack   = EXTI_L9_PB_IRQHandlerCallback;
	pin.IRQ_EN           = EXTI_IRQ_ENABLE;
	MCAL_EXTI_Init(&pin);
}



void EXTI_L9_PB_IRQHandlerCallback()
{
	IRQ_Flag = 1;
	LCD_Write_String("EXTI Line 9 IRQ was triggered..");
	_wait_ms(750);
}



int main(void)
{
	clock_init();
	LCD_Init();
	EXTI_init();
	_wait_ms(500);

	while(1)
	{
		if (IRQ_Flag)
		{
			LCD_Clear_Screen();
			IRQ_Flag = 0;
		}
	}

	return 0;
}
