/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "STM32F103x6.h"
#include "STM32F103x6_GPIO_Driver.h"
#include "Keypad.h"
#include "LCD.h"



void _wait_ms(uint32_t time)
{
	uint32_t i, j;
	for (i = 0; i < time; i++)
		for (j = 0; j < 255; j++) ;
}



void clock_init()
{
	//	GPIOA clock enable
	RCC_GPIOA_CLK_EN();

	//	GPIOB clock enable
	RCC_GPIOB_CLK_EN();
}



int main(void) {
	clock_init();
	LCD_Init();
	LCD_Write_String("LCD is ready...");
	_wait_ms(750);
	LCD_Clear_Screen();
	Keypad_Init();
	LCD_Write_String("Keypad is ready...");
	_wait_ms(750);
	LCD_Clear_Screen();
	unsigned int count = 0;
	unsigned char key_pressed;

	while(1) {
		key_pressed = Keypad_Get_Key();

		switch(key_pressed) {
			case 'A':
				break;
			case '!':
				count = 0;
				LCD_Clear_Screen();
				break;
			default:
				LCD_Write_Char(key_pressed);
				count++;
				if (count == 16) {
					LCD_GoTo_XY(2,0);
				} else if (count == 32) {
					LCD_Clear_Screen();
					LCD_GoTo_XY(1,0);
					count = 0;
				}
				break;
		}

	}

	return 0;
}
