/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "STM32F103x6.h"
#include "STM32F103x6_GPIO_Driver.h"
#include "LCD.h"



void _wait_ms(uint32_t time)
{
	uint32_t i, j;
	for (i = 0; i < time; i++)
		for (j = 0; j < 255; j++) ;
}



void clock_init()
{
	//	GPIOA clock enable
	RCC_GPIOA_CLK_EN();

	//	GPIOB clock enable
	RCC_GPIOB_CLK_EN();
}



int main(void)
{
	clock_init();
	LCD_Init();
	LCD_Write_String("LCD is ready...");
	_wait_ms(750);
	LCD_Clear_Screen();

	while(1)
	{
		LCD_Write_String("Hello!  I'm Mina Basally..");
		_wait_ms(500);
		LCD_Clear_Screen();
		LCD_Write_String("This is a brief Test to verify  my LCD-Driver...");
		_wait_ms(500);
		LCD_Clear_Screen();
		LCD_Write_String("Displaying a-   Real Number  :   ");
		LCD_Display_Real_Number(-90.07318);
		_wait_ms(500);
		LCD_Clear_Screen();
		LCD_Write_String("Displaying an-  Integer : ");
		LCD_Display_Number(99);
		_wait_ms(500);
		LCD_Clear_Screen();
		LCD_Write_String("Displaying      Custom Characte-rs :  ");
		LCD_Custom_Character();
		_wait_ms(750);
		LCD_Clear_Screen();
	}

	return 0;
}
